# -----------------------------------------------------------------------------
# Variables for the KVM/libvirt infrastructure
# -----------------------------------------------------------------------------

variable "libvirt_uri" {
  description = "Libvirt connection URI"
  type        = string
  default     = "qemu:///system"
}

variable "cluster_name" {
  description = "Name of the OpenShift cluster"
  type        = string
  default     = "lap-cluster"
}

variable "cluster_domain" {
  description = "Base domain for the cluster"
  type        = string
  default     = "lab.local"
}

variable "network_name" {
  description = "Name of the libvirt network"
  type        = string
  default     = "ocp-net"
}

variable "network_address" {
  description = "IP address of the cluster network gateway (IPv4)"
  type        = string
}

variable "network_prefix" {
  description = "Prefix of the cluster network (IPv4)"
  type        = number
  default     = 24
}

variable "network_ipv6_address" {
  description = "IP address of the cluster network gateway (IPv6)"
  type        = string
}

variable "network_ipv6_prefix" {
  description = "Prefix of the cluster network (IPv6)"
  type        = number
  default     = 64
}

variable "api_vip" {
  description = "Virtual IP for the API (IPv4)"
  type        = string
}

variable "api_vip_ipv6" {
  description = "Virtual IP for the API (IPv6)"
  type        = string
}

variable "ingress_vip" {
  description = "Virtual IP for Ingress (IPv4)"
  type        = string
}

variable "ingress_vip_ipv6" {
  description = "Virtual IP for Ingress (IPv6)"
  type        = string
}

variable "storage_pool_path" {
  description = "Path to the libvirt storage pool on the host"
  type        = string
  default     = "/var/lib/libvirt/images/ocp"
}

variable "agent_iso_path" {
  description = "Path to the Agent-Based Installer ISO (generated by Ansible)"
  type        = string
  default     = ""
}

# ---------- Node Definitions ----------

variable "controlplanes" {
  description = "List of controlplane nodes"
  type = list(object({
    name      = string
    vcpu      = number
    memory    = number # MiB
    disk_size = number # GiB
    mac       = string
    ip        = string
    ipv6      = string
  }))
}

variable "workers" {
  description = "List of worker nodes (optional)"
  type = list(object({
    name      = string
    vcpu      = number
    memory    = number
    disk_size = number
    mac       = string
    ip        = string
    ipv6      = string
  }))
  default = []
}
