# -----------------------------------------------------------------------------
# Variables for the KVM/libvirt infrastructure
# -----------------------------------------------------------------------------

variable "libvirt_uri" {
  description = "Libvirt connection URI"
  type        = string
  default     = "qemu:///system"
}

variable "cluster_name" {
  description = "Name of the OpenShift cluster"
  type        = string
  default     = "lap-cluster"
}

variable "cluster_domain" {
  description = "Base domain for the cluster"
  type        = string
  default     = "lab.local"
}

variable "network_name" {
  description = "Name of the libvirt network"
  type        = string
  default     = "ocp-net"
}

variable "network_cidr" {
  description = "CIDR of the cluster network"
  type        = string
  default     = "192.168.150.0/24"
}

variable "api_vip" {
  description = "Virtual IP for the API"
  type        = string
}

variable "ingress_vip" {
  description = "Virtual IP for Ingress"
  type        = string
}

variable "storage_pool_path" {
  description = "Path to the libvirt storage pool on the host"
  type        = string
  default     = "/var/lib/libvirt/images/ocp"
}

variable "agent_iso_path" {
  description = "Path to the Agent-Based Installer ISO (generated by Ansible)"
  type        = string
  default     = ""
}

# ---------- Node Definitions ----------

variable "masters" {
  description = "List of master nodes"
  type = list(object({
    name      = string
    vcpu      = number
    memory    = number # MiB
    disk_size = number # GiB
    mac       = string
    ip        = string
  }))
}

variable "workers" {
  description = "List of worker nodes (optional)"
  type = list(object({
    name      = string
    vcpu      = number
    memory    = number
    disk_size = number
    mac       = string
    ip        = string
  }))
  default = []
}
