---
# =============================================================================
# Phase 4 – Wait for OpenShift Installation to complete (Local)
# =============================================================================
- name: "Wait for OpenShift Installation"
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Wait for bootstrap to complete
      ansible.builtin.command:
        cmd: "{{ local_bin_dir }}/openshift-install agent wait-for bootstrap-complete --dir {{ local_workdir }}/cluster-config --log-level debug"
      environment:
        PATH: "{{ local_bin_dir }}:{{ ansible_env.PATH }}"
      async: 3600
      poll: 30
      register: bootstrap_wait

    - name: Wait for install to complete
      ansible.builtin.command:
        cmd: "{{ local_bin_dir }}/openshift-install agent wait-for install-complete --dir {{ local_workdir }}/cluster-config --log-level debug"
      environment:
        PATH: "{{ local_bin_dir }}:{{ ansible_env.PATH }}"
      async: 3600
      poll: 30
      register: install_wait
